### ISSUE TITLE
character encoding missing

### ISSUE THREAD

**Issue by paul-shannon** [paul-shannon/IJAL-interlinear#2]
@davidjamesbeck  (including this tag should result in an email to you)

Welcome, David!

You mentioned in email Wednesday:
````
I got an error trying to run the make command, something about a character encoding declaration missing in one of the files.
````
If you are able to reproduce that, perhaps you could capture a trace which includes
   - the python (or shell) commands you issued which led up to the bug
   - the exact text of the error message (which might include filename and line number)

**Comment by davidjamesbeck** [comment]
iMac-2:~ David$ cd /Users/David/OpenSource/github/IJAL-interlinear/ijal_interlinear/tests 
iMac-2:tests David$ make #
python test_MorphemeGloss.py
  File "test_MorphemeGloss.py", line 5
SyntaxError: Non-ASCII character '\xe2' in file test_MorphemeGloss.py on line 5, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
make: *** [morphemeGloss] Error 1
iMac-2:tests David$

**Comment by paul-shannon** [comment]
thanks, @davidjamesbeck.
I don't know why I do not see that error here.  In any case, following your email of 24 July,I just added
````
# -*- coding: utf-8 -*-
````
to the top of MorphemeGloss.py

Maybe that will be needed in all of the python files.

Try this?
     - ````cd /Users/David/OpenSource/github/IJAL-interlinear/ijal_interlinear````
     - ```` git pull ````
     - ````cd tests````
     - ````make````

**Comment by davidjamesbeck** [comment]
This didn’t work, exactly

iMac-2:tests David$ cd /Users/David/OpenSource/github/IJAL-interlinear/ijal_interlinear
iMac-2:ijal_interlinear David$ git pull
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 7 (delta 5), reused 7 (delta 5), pack-reused 0
Unpacking objects: 100% (7/7), done.
From https://github.com/paul-shannon/IJAL-interlinear
   250a578..ffbec94  master     -> origin/master
Updating 250a578..ffbec94
Fast-forward
 ijal_interlinear/morphemeGloss.py | 3 +++
 1 file changed, 3 insertions(+)
iMac-2:ijal_interlinear David$ cd tests
iMac-2:tests David$ make
python test_MorphemeGloss.py
  File "test_MorphemeGloss.py", line 5
SyntaxError: Non-ASCII character '\xe2' in file test_MorphemeGloss.py on line 5, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
make: *** [morphemeGloss] Error 1

But note that the error reported here is for test_MorphemeGloss.py. I went to that file and added as the first line of the file

# -*- coding: utf-8 -*-

Then I ran make again:

iMac-2:tests David$ make
python test_MorphemeGloss.py
Traceback (most recent call last):
  File "test_MorphemeGloss.py", line 4, in <module>
    from morphemeGloss import *
  File "../morphemeGloss.py", line 26
SyntaxError: Non-ASCII character '\xe2' in file ../morphemeGloss.py on line 26, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
make: *** [morphemeGloss] Error 1

morphemeGloss.py definitely has the encoding declaration (twice, in fact), but it isn’t the very first line in the file. Once I move it to the beginning of the file, it works:

iMac-2:tests David$ make
python test_MorphemeGloss.py
Traceback (most recent call last):
  File "test_MorphemeGloss.py", line 4, in <module>
    from morphemeGloss import *
  File "../morphemeGloss.py", line 37, in <module>
    from yattag import *
ImportError: No module named yattag
make: *** [morphemeGloss] Error 1

The error here is because my system “python" runs Python 2.7 (which I don’t really use and which I haven’t installed any of these packages for). “python3" runs Python 3.7, where all the site packages live. I’m not sure what to do about that—I’m afraid to change the invocation because there is probably software on the Mac that needs “python" to run 2.7 (which is what Apple is still building into the OS). Is there a way to change the command in Unix just for a particular session?

David

**Comment by paul-shannon** [comment]
I wondered if python 2.7 might be the problem.   Good.  Maybe python 3 has utf-8 by default?

If you use bash as your macOS shell (I think it is the default)

  echo $SHELL

then these bash commands will illuminate and allow you to invoke python 3

  type -a python   # reports all the python interpreters in your PATH
  PATH=/path/to/python3:$PATH    # ensures that python3 is found first

python 3 was released a decade ago.  It befuddles me that its use lingers on.

You could also experiment to make the switch to python 3 universal on your computer, by adding the PATH statement, above, to your ~/.bash_profile 

You can test the success of that modified PATH statement like this:

  - make the change to ~/.bash_profile
  - source ~/.bash_profile
  - type -a python

This is rather fussy stuff, sometimes takes a few tries to get it right.

Let me know how this goes.   Once you have your setup right, I propose that we explicitly require and test for python >= 3.6 in the project, if you are amenable.

 - Paul

**Comment by davidjamesbeck** [comment]
Hi, Paul

I can try that, but will it “undo” itself once I quit my terminal? I’m worried about making the changes in the path permanent. I have other software installed that might want 2.7 and Apple might as well. I guess if it is a persistent change I can still make it and then undo it if need be, or try to troubleshoot the other software. (And I agree, why are people still using Python 2 after all this time—it isn’t even that hard to port 2 to 3.)

I’m fine with having the project test for the right Python. It’s a good idea and nips the requirement that we support Python 2 in the bud.

David

**Comment by paul-shannon** [comment]
>  will it “undo” itself once I quit my terminal?

Yes, it would.

You could always create a ~/.setupPython3 script, which prepends the proper python3 directory to your PATH, and then invoke that script before you start working with our code.

After I made python3 the default on my laptop I noticed no problems.  But maybe I forgot some accomodations I had to make.

Let me know when I can add something like this to the module, perhaps only at one point in one file:

   import sys
   assert(sys.version_info >= (3, 6))

Maybe then we can eliminate the explicit utf-8 magic

 - Paul

**Comment by davidjamesbeck** [comment]
Messing around with the path didn’t seem to have any effect, 

iMac-2:tests David$ type -a python
python is /Library/Frameworks/Python.framework/Versions/2.7/bin/python
python is /Library/Frameworks/Python.framework/Versions/2.7/bin/python
python is /usr/local/bin/python
python is /usr/bin/python
iMac-2:tests David$ PATH=/path/to/python3:$PATH
iMac-2:tests David$ type -a python
python is /Library/Frameworks/Python.framework/Versions/2.7/bin/python
python is /Library/Frameworks/Python.framework/Versions/2.7/bin/python
python is /usr/local/bin/python
python is /usr/bin/python

but I set up an alias in the shell and that works on the command line. 

iMac-2:~ David$ alias python=python3
iMac-2:~ David$ python --version
Python 3.7.0

though it doesn’t change the output of type much

iMac-2:tests David$ type -a python
python is aliased to `python3'
python is /Library/Frameworks/Python.framework/Versions/2.7/bin/python
python is /Library/Frameworks/Python.framework/Versions/2.7/bin/python
python is /usr/local/bin/python
python is /usr/bin/python


But make still says it can’t find yattag, so I wonder if something is pointing make to Python 2 other than the shell?

I also tried editing the .bash_profile file, but that didn’t have any effect on python at all.

David

**Comment by paul-shannon** [comment]
I confused matters by using this not-so-obvious shorthand:

>    PATH=/path/to/python3:$PATH

“/path/to/“ is intended to be a placeholder, where the reader (unbeknownst to you!) is expected to substitute  ACTUAL directory names for “path” and “to” (and maybe more than 2 substitutions.

My python 3 is from anaconda:

dir /Users/paul/anaconda/bin/python  #  9 Feb 14  2018 /Users/paul/anaconda/bin/python -> python3.6
dir /Users/paul/anaconda/bin/python3 #  9 Feb 14  2018 /Users/paul/anaconda/bin/python3 -> python3.6

So here “/path/to” resolves to “/Users/paul/anaconda/bin"

You too should have a something similar, a /path/to/python which is truly a python version 3.x
The goal is to find out what you /path/to actually is.

Try this:

   type -a python3

This will give you a path - your value to substitute into /path/to/
And when you do dir (my alias for “ls -l”) on that file, you will probably also find that it is a symlink (that is, just another filename in a directory) to python 3.x

I put /Users/paul/anaconda/bin at the beginning of my PATH, so therefore /Users/paul/anaconda/bin/python is always picked up first.  

I hope this makes more sense!

 - Paul

**Comment by davidjamesbeck** [comment]
Oh, duuh. Sorry for being so obtuse. However, bash seems even more obtuse 

iMac-2:~ David$ type -a python3
python3 is /Library/Frameworks/Python.framework/Versions/3.7/bin/python3
python3 is /usr/local/bin/python3
iMac-2:~ David$ PATH=/Library/Frameworks/Python.framework/Versions/3.7/bin/python3:$PATH
iMac-2:~ David$ type -a python
python is /Library/Frameworks/Python.framework/Versions/2.7/bin/python
python is /usr/local/bin/python
python is /usr/bin/python

I already have in my .bash_profile the statement

PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:${PATH}"
export PATH

put there by the UpdateShell script that comes with the Python distribution. I tried adding either

PATH=“/Library/Frameworks/Python.framework/Versions/3.7/bin/python3:${PATH}"

or just

PATH=/Library/Frameworks/Python.framework/Versions/3.7/bin/python3:$PATH
export PATH

to .bash_profile, but that didn’t seem to make any difference either. I confess to having a poor relationship with UNIX, so I might be missing something obvious (like, is bash really using the .bash_profile at the top level of my user directory? I don’t know why it wouldn’t be, but I also don’t know how to check).

David

**Comment by paul-shannon** [comment]
Yep, all these arbitrary details which have to be just so - it’s enough to annoy, certainly, and often to drive one to distraction.

One thing you may not yet see:  the directories in the path do not name the program, but the directory in which it is found.

So this is not a proper PATH directory:

   /Library/Frameworks/Python.framework/Versions/3.7/bin/python3

But this is:

  /Library/Frameworks/Python.framework/Versions/3.7/bin

Therefore you want to have this in ~/.bash_profile

  PATH=/Library/Frameworks/Python.framework/Versions/3.7/bin:$PATH

But first, execute that line directly in the bash shell:

  bash> PATH=/Library/Frameworks/Python.framework/Versions/3.7/bin:$PATH
  bash> echo $PATH

make sure that /Library/Frameworks/Python.framework/Versions/3.7/bin 
comes first

Then this next command should work - as long as there is indeed a

 /Library/Frameworks/Python.framework/Versions/3.7/bin/python 

as well as a python3 in that directory: 


   bash> type python   # type -a python will list ALL the pythons in all of your PATH directories
   python is  /Library/Frameworks/Python.framework/Versions/3.7/bin/python

When this works, directly in the shell, then add it to ~/.bash_profile - which is only read and executed when you create a new shell.   Therefore to try it out in your current shell, you must execute it explicitly:

   bash> source ~/.bash_profile

Then try 

   bash> type python 

When that works, then open up a new shell, and make sure it still works.

This is confusing stuff.  Let’s work it out over the phone if it still appears broken.

 - Paul

**Comment by davidjamesbeck** [comment]
Hi, Paul

Okay, that does make sense, and it’s the kind of error I like because the reason it is an error makes sense. However, it doesn’t seem to fix things

iMac-2:~ David$ echo $PATH
/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
iMac-2:~ David$ PATH=/Library/Frameworks/Python.framework/Versions/3.7/bin:$PATH
iMac-2:~ David$ echo $PATH
/Library/Frameworks/Python.framework/Versions/3.7/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
iMac-2:~ David$ type python
python is /Library/Frameworks/Python.framework/Versions/2.7/bin/python
iMac-2:~ David$ type python3
python3 is /Library/Frameworks/Python.framework/Versions/3.7/bin/python3

I initially though that the error might be because there was no file called “python” in the …/bin/ directory. And indeed there wasn’t, so I made an alias named “python” that points to the python3.7 file in that directory (which is what the python3 alias points to). But I still get the results above.

Anyway, I have to go out now, but if you have time tomorrow and think that we can resolve this over the phone, we can talk then. I’ll keep mulling this over to see if anything not-too-desparate sounding occus to me.

And thanks for the patience. I frequent programmer forums from time to time and post naïve questions, and rarely get civil or patient responses. 

Cheers,

David

**Comment by paul-shannon** [comment]
Hi David,

You are looking at it just right, I think.

Making an alias is a step in the right direction.   I wonder, though:  did you do it like this?

  alias python=/Library/Frameworks/Python.framework/Versions/3.7/bin/python3

That ought to work but since it seems that it did not (leaving me confused) perhaps it is also worth trying a symlink - also called a soft link.

By contrast, a hard link is a second entry in the file system that points to an already named file.

A symlink (soft link) is an entry in the file system, found in a specific directory, whose contents is only the path to the linked file.   The symlink’s entry is the file system identifies as a link file:

lrwxr-xr-x  1 paul  staff        9 Feb 14  2018 /Users/paul/anaconda/bin/python -> python3.6
lrwxr-xr-x  1 paul  staff        9 Feb 14  2018 /Users/paul/anaconda/bin/python3 -> python3.6
-rwxrwxr-x  1 paul  staff  3504976 Feb 14  2018 /Users/paul/anaconda/bin/python3.6

The real executable is python3.6, 3.5M in size, filetype marked (implicitly via “-“ in column 1) as a “regular file”.   python3 and python3.6 are symlinks, marked “l” in the first column.   You can see that their contents is only 9 bytes long, the character count on the string “python3.6”.

All three lines have a count of one: see the second column above.   If the two symlinks were actually hard links, all three would have a length of 3.5MB, and their counts would be three.

To create a symlink, if you want to try this, here is what you do:

   cd <your python3 bin directory>
   ln -s python3.6 python   

The -s is for “soft”.  If you omitted that, you would create a hard link - which you don’t need to do.

Worth a try?

If this remains unworkable, let’s talk by phone this evening.  

I admire your patience!

 - paul

**Comment by davidjamesbeck** [comment]
Hi, Paul

Okay, that seems to have had some effect:

iMac-2:~ David$ cd /Library/Frameworks/Python.framework/Versions/3.7/bin
iMac-2:bin David$ ln -s python3.7 python
ln: python: File exists

at this point I manually removed the hard link I created yesterday 

iMac-2:bin David$ ln -s python3.7 python
iMac-2:bin David$ type -a python
python is /Library/Frameworks/Python.framework/Versions/2.7/bin/python
python is /Library/Frameworks/Python.framework/Versions/3.7/bin/python
python is /usr/local/bin/python
python is /usr/bin/python

so now “type” finds both Pythons but, I think, in the wrong order, though I can now do

iMac-2:bin David$ PATH=/Library/Frameworks/Python.framework/Versions/3.7/bin:$PATH
iMac-2:bin David$ type python
python is /Library/Frameworks/Python.framework/Versions/3.7/bin/python

and then I can run make in the tests folder without any problems that I can see

> On Oct 14, 2018, at 12:08 PM, Paul Shannon <notifications@github.com> wrote:
> 
> Hi David,
> 
> You are looking at it just right, I think.
> 
> Making an alias is a step in the right direction. I wonder, though: did you do it like this?
> 
> alias python=/Library/Frameworks/Python.framework/Versions/3.7/bin/python3

I created the alias using the MacOS Finder (control-click on the target, select “Make Alias” from the context menu, rename the file “python”). I’ll chalk up the failure “just one of those things”. There are a lot of those things …

Thanks for the help here. Patience pays off when you learn something, which isn’t always the outcome, even if you’re successful.

Cheers

David
> 
> That ought to work but since it seems that it did not (leaving me confused) perhaps it is also worth trying a symlink - also called a soft link.
> 
> By contrast, a hard link is a second entry in the file system that points to an already named file.
> 
> A symlink (soft link) is an entry in the file system, found in a specific directory, whose contents is only the path to the linked file. The symlink’s entry is the file system identifies as a link file:
> 
> lrwxr-xr-x 1 paul staff 9 Feb 14 2018 /Users/paul/anaconda/bin/python -> python3.6
> lrwxr-xr-x 1 paul staff 9 Feb 14 2018 /Users/paul/anaconda/bin/python3 -> python3.6
> -rwxrwxr-x 1 paul staff 3504976 Feb 14 2018 /Users/paul/anaconda/bin/python3.6
> 
> The real executable is python3.6, 3.5M in size, filetype marked (implicitly via “-“ in column 1) as a “regular file”. python3 and python3.6 are symlinks, marked “l” in the first column. You can see that their contents is only 9 bytes long, the character count on the string “python3.6”.
> 
> All three lines have a count of one: see the second column above. If the two symlinks were actually hard links, all three would have a length of 3.5MB, and their counts would be three.
> 
> To create a symlink, if you want to try this, here is what you do:
> 
> cd <your python3 bin directory>
> ln -s python3.6 python 
> 
> The -s is for “soft”. If you omitted that, you would create a hard link - which you don’t need to do.
> 
> Worth a try?
> 
> If this remains unworkable, let’s talk by phone this evening. 
> 
> I admire your patience!
> 
> - paul
> 
>
